name: Trigger auto deployment for container-app-o7wxs3lkqlcqq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-o7wxs3lkqlcqq-AutoDeployTrigger-7d9042b6-b94f-4699-a35f-a50ac5476aa3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPO7WXS3LKQLCQQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPO7WXS3LKQLCQQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPO7WXS3LKQLCQQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPO7WXS3LKQLCQQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPO7WXS3LKQLCQQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-o7wxs3lkqlcqq
          resourceGroup: appspacesfastapib89687d9
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


